version: "3.9"
services:
  gitea:
    image: gitea/gitea:1.17.3
    ports:
      - "3000:3000"
      - "3022:22"
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__security__SECRET_KEY=FB280ULDaz5zIgU
      - GITEA__security__INTERNAL_TOKEN=admin123FB280ULDaz5zIgU
    volumes:
      - gitea_data:/data
volumes:
  gitea_data: