version: "3.9"
services:
  api:
    image: unlockprogramming/cloudlab/text-sentiment-scores-api
    restart: on-failure
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:80"